const typesError = {
    NOT_FOUND: 'NOT_FOUND',
    BAD_REQUEST: 'BAD_REQUEST',
    FORMAT_ERROR: 'FORMAT_ERROR',
    INVALID_BUSINESS_RULE: 'INVALID_BUSINESS_RULE',
    PROCESS_FAILURE: 'PROCESS_FAILURE',
    DATA_VALIDATION_ERROR: 'DATA_VALIDATION_ERROR',
    SYSTEM_ERROR: 'SYSTEM_ERROR',
    DEFAULT_ERROR: 'DEFAULT_ERROR',
    FORBIDDEN_ERROR: 'FORBIDDEN_ERROR',
    UNAUTHORIZED_ERROR: 'UNAUTHORIZED_ERROR',
    CONFLICT_ERROR: 'CONFLICT_ERROR'
  };
  
export enum EnumErrorCodes {
    NOT_FOUND = 404,
    BAD_REQUEST = 400,
    FORMAT_ERROR = 400,
    INVALID_BUSINESS_RULE = 422,
    PROCESS_FAILURE = 422,
    DATA_VALIDATION_ERROR =  422,
    DEFAULT_ERROR = 500,
    SYSTEM_ERROR = 500,
    FORBIDDEN_ERROR = 403,
    UNAUTHORIZED_ERROR = 401,
    CONFLICT_ERROR = 409,  
    REQUEST_TIMEOUT_ERROR = 504
}
  export default typesError;